Django code/bookmanage/bookmanage/urls.py
from django.conf.urls import url
from django.contrib import admin
from app01 import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^publisher_list/', views.publisher_list),
    url(r'^publisher_add/', views.publisher_add),
    url(r'^publisher_del/', views.publisher_del),
    url(r'^publisher_edit/', views.publisher_edit),
    url(r'^home_page/', views.home_page),
    url(r'^book_list/', views.book_list),
    url(r'^book_add/', views.book_add),
    url(r'^book_del/', views.book_del),
    url(r'^book_edit/', views.book_edit),
    url(r'^author_list/', views.author_list),
    url(r'^author_add/', views.author_add),
    url(r'^author_del/', views.author_del),
    url(r'^author_edit/', views.author_edit),


]

Django code/bookmanage/app01/models.py
from django.db import models

class bookmanage(models.Model):
    pid = models.AutoField(primary_key=True)
    name=models.CharField(max_length=32,unique=True)

    def __str__(self):
        return '{} {}'.format(self.pid,self.name)


class book(models.Model):
    bid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=32)
    pub = models.ForeignKey('bookmanage',on_delete=models.CASCADE)

    def __str__(self):
        return '{} {} {}'.format(self.bid,self.name,self.pub_id)

class author(models.Model):
    name=models.CharField(max_length=32)
    books = models.ManyToManyField(book)

Django code/bookmanage/app01/views.py
from django.shortcuts import render,HttpResponse,redirect
from app01 import models
from django.views import View
def publisher_list(request):
    all_publishers=models.bookmanage.objects.all().order_by('pid')
    return render(request,'publisher_list.html',{'all_publishers':all_publishers})
def publisher_add(request):
    error=''
    value=''
    if request.method =='POST':
        pub_name = request.POST.get('publisher_name')
        if pub_name:
            if models.bookmanage.objects.filter(name=pub_name):
                error='提交的内容重复'
                value=pub_name
            else:
                obj = models.bookmanage.objects.create(name=pub_name)
                return redirect('/publisher_list/')
        else:
            error='不能为空'
    return render(request,'publisher_add.html',{'error':error,'value':value})
def publisher_del(request):
    error=''
    # models.bookmanage.objects.
    pk_book = request.GET.get('pk')
    query = models.bookmanage.objects.filter(pid=pk_book)
    if query:
        query.delete()
        return redirect('/publisher_list/')
    else:return HttpResponse('要删除的内容不存在')
def publisher_edit(request):
    pk=request.GET.get('pk')
    obj = models.bookmanage.objects.filter(pk=pk).first()
    if not obj:
        return HttpResponse('要编辑的对象不存在')
    error=''
    if request.method=='POST':
        pub_name = request.POST.get('pub_name')
        if not pub_name:
            error = '不能为空'
        else:
            if not models.bookmanage.objects.filter(name=pub_name):
                obj.name = pub_name
                obj.save()
                return redirect('/publisher_list/')
            elif obj.name==pub_name:
                error='没有做修改'
            else:error='这个出版社已存在'
    return render(request, 'publisher_edit.html', {'obj': obj,'error':error})
def home_page(request):
    return render(request,'home_page.html')
def book_list(request):
    all_book=models.book.objects.all()
    return render(request,'book_list.html',{'all_book':all_book})
def book_add(request):
    error=''
    if request.method=='POST':
        book_name = request.POST.get('book_name')
        pub_id = request.POST.get('pub_id')
        if not book_name:
            error = '不能为空'
        else:
            ret=models.book.objects.create(name=book_name,pub_id=pub_id)
            return redirect('/book_list/')
    all_publishers=models.bookmanage.objects.all().order_by('pid')
    return render(request,'book_add.html',{'all_publishers':all_publishers,'error':error})
def book_del(request):
    pk=request.GET.get('pk')
    ret = models.book.objects.filter(pk=pk)
    if not ret:
        return HttpResponse('要删除的内容不存在')
    ret.delete()
    return redirect('/book_list/')
def book_edit(request):
    error=''
    book_id=request.GET.get('pk')
    query = models.book.objects.filter(pk=book_id).first()
    value=query.name
    pub_id=query.pub_id
    all_publishers=models.bookmanage.objects.all()
    if request.method=='POST':
        book_name = request.POST.get('book_name')
        if book_name:
            pub_id = request.POST.get('pub_id')
            query.name=book_name
            query.pub_id=pub_id
            query.save()
            return redirect('/book_list/')
        else:error='不能为空'

    return render(request,'book_edit.html',{'value':value,'error':error,'all_publishers':all_publishers,'pub_id':pub_id})
def author_list(request):
    all_author = models.author.objects.all()
    return render(request,'author_list.html',{'all_author':all_author})
def author_add(request):
    all_books=models.book.objects.all()
    error=''
    if request.method=="POST":
        name = request.POST.get('name')
        books=request.POST.getlist('books')
        if not name:
            error='不能为空'
        else:
            author_obj=models.author.objects.create(name=name)
            author_obj.books.set(books)
            return redirect('/author_list/')

    return render(request,'author_add.html',{'all':all_books,'error':error})
def author_del(request):
    pk=request.GET.get('pk')
    if not pk:
        return HttpResponse('要删除的内容不存在')
    else:
        models.author.objects.get(pk=pk).delete()
    return redirect('/author_list/')
# def author_edit(request):
#     error=''
#     pk=request.GET.get('pk')
#     author=models.author.objects.filter(pk=pk).first()
#     all_books=models.book.objects.all()
#     if request.method == 'POST':
#         name = request.POST.get('name')
#         books=request.POST.getlist('books')
#         if not name:
#             error='不能为空'
#         else:
#             author.name=name
#             author.save()
#             author.books.set(books)
#             return redirect('/author_list/')
#
#     return render(request,'author_edit.html',{'author':author,'all_books':all_books,'error':error})

class author_edit(View):
    def get(self,request):
        pk = request.GET.get('pk')
        author = models.author.objects.filter(pk=pk).first()
        all_books = models.book.objects.all()
        return render(request,'author_edit.html',{'author':author,'all_books':all_books})
    def post(self,request):
        pk = request.GET.get('pk')
        author = models.author.objects.filter(pk=pk).first()
        all_books = models.book.objects.all()
        name = request.POST.get('name')
        books = request.POST.getlist('books')
        if not name:
            error = '不能为空'
        else:
            author.name = name
            author.save()
            author.books.set(books)
            return redirect('/author_list/')
        return render(request, 'author_edit.html', {'author': author, 'all_books': all_books,'error':error})

Django code/bookmanage/templates/author_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>增加作者</title>
</head>
<body>
<form action="" method="post">
    <p><input type="text" name="name"><span style="color: red">{{ error }}</span></p>
        <p><select name="books" id="" multiple>
                {% for book in all %}
                    <option value="{{ book.pk }}">{{ book.name }}</option>
                {% endfor %}
            </select>
        </p>
<button>提交</button>
</form>
</body>
</html>

Django code/bookmanage/templates/author_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">
    <p><input type="text" name="name" value="{{ author.name }}"><span style="color: red">{{ error }}</span></p>
        <p><select name="books" id="" multiple size="10">
                {% for book in all_books %}
                    {% if book in author.books.all %}
                    <option value="{{ book.pk }}" selected>{{ book.name }}</option>
                    {% endif %}
                    <option value="{{ book.pk }}">{{ book.name }}</option>
                {% endfor %}
            </select>
        </p>
<button>提交</button>
</form>
</body>
</html>

Django code/bookmanage/templates/author_list.html
{% extends 'base.html' %}
{% block title %}作者列表{% endblock %}
{% block add %}author_add{% endblock %}
{% block authorlable %}active{% endblock %}
{% block subject %}
    <thead>
    <tr>
        <th>序号</th>
        <th>ID</th>
        <th>姓名</th>
        <th>作品</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody>
    {% for author in all_author %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ author.pk }}</td>
            <td>{{ author.name }}</td>
            <td>
                {% for book in author.books.all %}
                    《{{ book.name }}》
                {% endfor %}
            </td>
            <td><a class="btn btn-danger" href="/author_del/?pk={{ author.pk }}">删除</a>
                <a class="btn btn-warning" href="/author_edit/?pk={{ author.pk }}">编辑</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
{% endblock %}

Django code/bookmanage/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>图书管理系统</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/dashboard.css">
    <style>
        .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
    padding: 8px;
    {#line-height: 1.42857143;#}
    vertical-align: middle;
    border-top: 1px solid;}
    </style>

</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">图书管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">导航</a></li>
                <li><a href="#">设置</a></li>
                <li><a href="#">配置文件</a></li>
                <li><a href="#">帮助</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="搜索...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li class="{% block publable %}{% endblock %}"><a href="/publisher_list/">出版社列表<span class="sr-only">(小标)</span></a></li>
                <li class="{% block booklable %}{% endblock %}"><a href="/book_list/">图书列表<span class="sr-only">(current)</span></a></li>
                <li class="{% block authorlable %}{% endblock %}"><a href="/author_list/">作者列表<span class="sr-only">(current)</span></a></li>
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h2 class="sub-header">{% block title %}{% endblock %}</h2>
            <a class="btn btn-info" href="/{% block add %}{% endblock %}/">添加</a>
            <div class="table-responsive">
                <table class="table table-striped">
                    {% block subject %}
                    {% endblock %}
                </table>
            </div>
        </div>
    </div>
</div>

</body>

</html>

Django code/bookmanage/templates/book_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>新增图书</title>
</head>
<body>
<form action="" method="post">
    <p><input type="text" name="book_name" value="{{ value }}"><span style="color:red">{{ error }}</span></p>
    <p><select name="pub_id" id="">
        {% for all_publisher in all_publishers %}
            <option value="{{ all_publisher.pk }}">{{all_publisher.name }}</option>
        {% endfor %}
    </select></p>
    <input type="submit">
</form>
</body>
</html>

Django code/bookmanage/templates/book_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>图书编辑</title>
</head>
<body>
<form action="" method="post">
    <p><input type="text" name="book_name" value="{{ value }}"><span style="color:red">{{ error }}</span></p>
    <p><select name="pub_id" id="">
        {% for all_publisher in all_publishers %}
            {% if all_publisher.pk == pub_id %}
            <option selected value="{{ all_publisher.pk }}">{{all_publisher.name }}</option>
                {% else %}
                <option value="{{ all_publisher.pk }}">{{all_publisher.name }}</option>
            {% endif %}

        {% endfor %}
    </select></p>
    <input type="submit">
</form>
</body>
</html>

Django code/bookmanage/templates/book_list.html
{% extends 'base.html'  %}
{% block title %}图书列表{% endblock %}
{% block add %}book_add{% endblock %}
{% block booklable %}active{% endblock %}
{% block subject %}
    <thead>
                    <tr>
                        <th>序号</th>
                        <th>ID</th>
                        <th>书名</th>
                        <th>作者</th>
                        <th>出版社</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for i in all_book %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ i.pk }}</td>
                            <td>{{ i.name }}</td>
                            <td>
                                {% for author in i.author_set.all %}
                                    {{ author.name }}
                                {% endfor %}
                            </td>
                            <td>{{ i.pub.name }}</td>
                            <td><a class="btn btn-danger" href="/book_del/?pk={{ i.pk }}">删除</a>
                                <a class="btn btn-warning" href="/book_edit/?pk={{ i.pk }}">编辑</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
{% endblock %}

Django code/bookmanage/templates/home_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>图书管理系统</title>
</head>
<body>
<a href="/publisher_list/">出版社列表</a>
<a href="/book_list/">图书列表</a>
<a href="/author_list/">作者列表</a>
</body>
</html>

Django code/bookmanage/templates/publisher_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">
    <p><input type="text" name="publisher_name" value="{{ value }}"><span style="color:red">{{ error }}</span></p>
    <input type="submit">
</form>
</body>
</html>

Django code/bookmanage/templates/publisher_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑</title>
</head>
<body>
<form action="" method="post">
    <p><input type="text" name="pub_name" value="{{ obj.name }}"><span style="color:red">{{ error }}</span>
</p>
    <button>提交</button>
</form>

</body>
</html>

Django code/bookmanage/templates/publisher_list.html
{% extends 'base.html' %}
{% block title %}出版社列表{% endblock %}
{% block add %}publisher_add{% endblock %}
{% block publable %}active{% endblock %}
{% block subject %}
    <thead>
    <tr>
        <th>序号</th>
        <th>ID</th>
        <th>出版社</th>
        <th>操作</th>

    </tr>
    </thead>
    <tbody>
    {% for i in all_publishers %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ i.pk }}</td>
            <td>{{ i.name }}</td>
            <td><a class="btn btn-danger" href="/publisher_del/?pk={{ i.pk }}">删除</a> <a class="btn btn-warning" href="/publisher_edit/?pk={{ i.pk }}">编辑</a></td>
        </tr>
    {% endfor %}
    </tbody>
{% endblock %}